site_name: Wopee.io
nav:
  - 🚀 Autonomous Testing: index.md
  - Self-driving Bot...:
      - 🤖 Getting started: bot.md
      - 🛠️ Before method: before-method.md
  - Visual Testing with...:
      - ≫ Cypress:
          - Getting started: cypress/01-getting-started.md
          - Template project: cypress/02-template-project.md
          - Install plugin: cypress/03-install-plugin.md
      - ≫ Playwright: playwright-visual-testing.md
      - ≫ WebdriverIO: webdriverio-visual-testing.md
      - ≫ Robot Framework:
          - Getting started: robot-framework/01-getting-started.md
          - Manual setup: robot-framework/02-manual-setup.md
          - Setup with make: robot-framework/03-setup-with-make.md
          - Examples: robot-framework/04-some-more-examples.md
  - Other docs:
      - 📖 Glossary: glossary.md

theme:
  name: material
  language: en
  palette:
    # Palette toggle for light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: amber
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: amber
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - toc.integrate
    - navigation.top
    - navigation.footer
    - content.code.copy

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/wopee/
    - icon: fontawesome/brands/github
      link: https://github.com/Wopee-io

  analytics:
    provider: google
    property: G-PVTHWLV51B

extra_css:
  - css/custom.css

extra_javascript:
  - js/custom.js

plugins:
  - redirects:
      redirect_maps:
        "integrations/cypress/01-getting-started.md": "cypress/01-getting-started.md"
        "cypress.md": "cypress/01-getting-started.md"
        "cy.md": "cypress/01-getting-started.md"
        "integrations/playwright/01-getting-started.md": "playwright-visual-testing.md"
        "playwright.md": "playwright-visual-testing.md"
        "pw.md": "playwright-visual-testing.md"
        "integrations/webdriverio/01-getting-started.md": "webdriverio-visual-testing.md"
        "webdriverio.md": "webdriverio-visual-testing.md"
        "wdio.md": "webdriverio-visual-testing.md"
        "integrations/robot-framework/01-getting-started.md": "robot-framework/01-getting-started.md"
        "robot-framework.md": "robot-framework/01-getting-started.md"
        "rf.md": "robot-framework/01-getting-started.md"

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.superfences
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
